### ISSUE TITLE
Issue when building

### ISSUE THREAD

**Issue by omar2205** [lukasgeiter/mkdocs-awesome-pages-plugin#6]
Hi
I had a project working 4 days ago (Building without any problems)
But now, every time I try to build I get this error
mkdocs_awesome_pages_plugin.factory.PageNotFoundError: Page "index.md" not found. [.pages]

**Comment by omar2205** [comment]
> Traceback (most recent call last):
>   File "/usr/local/bin/mkdocs", line 11, in <module>
>     sys.exit(cli())
>   File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python3.4/dist-packages/mkdocs/__main__.py", line 163, in build_command
>     ), dirty=not clean)
>   File "/usr/local/lib/python3.4/dist-packages/mkdocs/commands/build.py", line 237, in build
>     config = config['plugins'].run_event('config', config)
>   File "/usr/local/lib/python3.4/dist-packages/mkdocs/plugins.py", line 94, in run_event
>     result = method(item, **kwargs)
>   File "/usr/local/lib/python3.4/dist-packages/mkdocs_awesome_pages_plugin/plugin.py", line 28, in on_config
>     pages = Factory(options).create(self._get_mkdocs_nav(config))
>   File "/usr/local/lib/python3.4/dist-packages/mkdocs_awesome_pages_plugin/factory.py", line 43, in create
>     children = self.arrange_pages(children, pages_file)
>   File "/usr/local/lib/python3.4/dist-packages/mkdocs_awesome_pages_plugin/factory.py", line 125, in arrange_pages
>     raise PageNotFoundError(path, pages_file.path)
> mkdocs_awesome_pages_plugin.factory.PageNotFoundError: Page "index.md" not found. [.pages]

**Comment by omar2205** [comment]
it seems it can't find the files, although they are exist
![](https://i.imgur.com/CQGtJW0.png)

**Comment by omar2205** [comment]
if I changed filename (in plugins options) to something else ex `.ind` it solves it 
but when I return it to `.pages` the error returns.

What could be the problem?

**Comment by lukasgeiter** [comment]
I'm happy to inform you that MkDocs 1.0 support has just landed in v2.0.0
